#pragma once

#define USB_POLLING_INTERVAL_MS 1
#define QMK_KEYS_PER_SCAN 12
#define DRIVER_LED_TOTAL RGB_MATRIX_LED_COUNT

#define OPENRGB_DIRECT_MODE_USE_UNIVERSAL_BRIGHTNESS

#undef PRODUCT
#define PRODUCT "V1"

#undef MANUFACTURER
#define MANUFACTURER "Keychron"
